"""CSC111 Winter 2026 Project 2: Anime Recommendation System (User Reviews)

Module Description
==================
This module implements a weighted user-anime graph for user-based anime recommendations.
Users and anime are represented as vertices, and edges connect users to anime they have
reviewed. Each edge weight stores the rating a user gave that anime.

Recommendations are generated by first computing cosine similarity between users. Then,
each anime’s score is computed by summing ratings from similar users, weighted by their similarity,
and dividing by the total similarity to obtain a weighted average. This score is then adjusted based on
the number of contributing users to penalize anime having less users in the top users and lower sample sizes.

This file is Copyright (c) 2026 Lily Annelise Canete-Goodine, Parmida Arab, Miray Ozdemir, Edwin Zeng
"""
from __future__ import annotations
import data_sanitization
import user_graph


class _WeightedVertex:
    """A vertex in a weighted graph, used to represent a user or an anime.

    Each vertex item is either a user id or anime title. Both are represented as strings.
    Neighbours are now a dictionary mapping from a neighbour vertex to the weight of the edge to from self to
    that neighbour.

    Copies CSC111 A3 _WeightedVertex class, except for similarity_score_weighted method.

    Instance Attributes:
        - item: The data stored in this vertex, representing a user or anime.
        - kind: The type of this vertex: 'user' or 'anime'.
        - neighbours: The vertices that are adjacent to this vertex and the edges contain the corresponding weights.

    Representation Invariants:
        - self not in self.neighbours
        - all(self in u.neighbours for u in self.neighbours)
        - self.kind in {'user', 'anime'}
    """
    item: str
    kind: str
    neighbours: dict[_WeightedVertex, float]

    def __init__(self, item: str, kind: str) -> None:
        """Initialize a new vertex with the given item and kind.

        This vertex is initialized with no neighbours.

        Preconditions:
            - kind in {'user', 'anime'}
        """
        self.item = item
        self.kind = kind
        self.neighbours = {}

    def degree(self) -> int:
        """Return the degree of this vertex."""
        return len(self.neighbours)

    def similarity_score_unweighted(self, other: _WeightedVertex) -> float:
        """Return the similarity score between this vertex and other, without using the edge weights.
        """
        if self.degree() == 0 or other.degree() == 0:
            return 0
        return (len(set(self.neighbours.keys()).intersection(other.neighbours))
                / len(set(self.neighbours.keys()).union(other.neighbours)))

    def similarity_score_weighted(self, other: _WeightedVertex) -> float:
        """Return cosine similarity between this user and other based on shared anime ratings."""
        common_anime = set(self.neighbours).intersection(other.neighbours)
        if len(common_anime) < 2:
            return 0.0
        numerator = 0.0
        sum_sq_self = 0.0
        sum_sq_other = 0.0
        for anime in common_anime:
            r1 = self.neighbours[anime]
            r2 = other.neighbours[anime]
            numerator += r1 * r2
            sum_sq_self += r1 ** 2
            sum_sq_other += r2 ** 2
        if sum_sq_self == 0 or sum_sq_other == 0:
            return 0.0

        return numerator / ((sum_sq_self ** 0.5) * (sum_sq_other ** 0.5))


class WeightedGraph(user_graph.Graph):
    """A graph used to represent a profile-anime network.
    Structure copied from CSC111 A3 WeightedGraph class, added/modified methods those in user_graph.Graph,
    add_input_user, get_top_similar_users, _score_candidate_anime, and recommend_anime.

    """
    # Private Instance Attributes:
    #     - _vertices:
    #         A collection of the vertices contained in this graph.
    #         Maps item to _Vertex object.
    _vertices: dict[str, _WeightedVertex]

    def __init__(self) -> None:
        """Initialize an empty graph (no vertices or edges)."""
        user_graph.Graph.__init__(self)
        self._vertices = {}

    def add_vertex(self, item: str, kind: str) -> None:
        """Add a vertex with the given item and kind to this graph.

        The new vertex is not adjacent to any other vertices.
        Do nothing if the given item is already in this graph.

        Preconditions:
            - kind in {'user', 'anime'}
        """
        if item not in self._vertices:
            self._vertices[item] = _WeightedVertex(item, kind)

    def add_edge(self, item1: str, item2: str, weight: float = 1.0) -> None:
        """Add an edge between the two vertices with the given items in this graph.

        Raise a ValueError if item1 or item2 do not appear as vertices in this graph.

        Preconditions:
            - item1 != item2
        """
        if item1 in self._vertices and item2 in self._vertices:
            v1 = self._vertices[item1]
            v2 = self._vertices[item2]

            v1.neighbours[v2] = weight
            v2.neighbours[v1] = weight
        else:
            raise ValueError

    def add_input_user(self, inputted_anime: dict[str, int], input_username: str) -> None:
        """
        Deletes existing vertex with item input_username if necessary, then adds a new ones to represent the input user
        and their inputted list of anime.
        """
        if input_username in self._vertices:
            v = self._vertices[input_username]
            for neighbour in v.neighbours:
                del neighbour.neighbours[v]
            del self._vertices[input_username]
        self.add_vertex(input_username, "user")
        for anime in inputted_anime:
            self.add_vertex(anime, "anime")
            self.add_edge(anime, input_username, inputted_anime[anime])

    def get_weight(self, item1: str, item2: str) -> float:
        """Return the weight of the edge between the given items.

        Return 0 if item1 and item2 are not adjacent.

        Preconditions:
            - item1 and item2 are vertices in this graph
        """
        v1 = self._vertices[item1]
        v2 = self._vertices[item2]
        return v1.neighbours.get(v2, 0)

    def get_similarity_score(self, item1: str, item2: str, score_type: str = "unweighted") -> float:
        """Return the similarity score between the two given items in this graph.

        score_type is one of 'unweighted' or 'weighted', corresponding to the
        different ways of calculating weighted graph vertex similarity.

        Raise a ValueError if item1 or item2 do not appear as vertices in this graph.

        Preconditions:
            - score_type in {'unweighted', 'weighted'}

        >>> g = WeightedGraph()
        >>> g.add_vertex('u1', 'user')
        >>> g.add_vertex('u2', 'user')
        >>> g.add_vertex('a1', 'anime')
        >>> g.add_vertex('a2', 'anime')
        >>> g.add_vertex('a3', 'anime')

        >>> g.add_edge('u1', 'a1', 5)
        >>> g.add_edge('u1', 'a2', 3)
        >>> g.add_edge('u2', 'a1', 4)
        >>> g.add_edge('u2', 'a2', 3)

        >>> round(g.get_similarity_score('u1', 'u2', 'weighted'), 3)
        0.995
        """
        if item1 not in self._vertices or item2 not in self._vertices:
            raise ValueError
        if score_type == "unweighted":
            return self._vertices[item1].similarity_score_unweighted(self._vertices[item2])
        else:
            return self._vertices[item1].similarity_score_weighted(self._vertices[item2])

    def get_top_similar_users(self, inputted_username: str, limit_users: int) -> dict[str, float]:
        """Return up to <limit_users> top similar users by similarity score, mapped to similarity score."""
        neighbour_users_to_score = []
        for user_id in self.get_all_vertices(kind='user'):
            if user_id == inputted_username:
                continue
            sim_score = self.get_similarity_score(user_id, inputted_username, "weighted")
            if sim_score != 0:
                neighbour_users_to_score.append((user_id, sim_score))
        neighbour_users_to_score.sort(key=lambda x: x[1], reverse=True)
        return dict(neighbour_users_to_score[:limit_users])

    def _score_candidate_anime(self, candidate_anime: set[str], top_users: dict[str, float]) -> dict[str, float]:
        """Return normalized recommendation scores for each candidate anime, gathered from the anime of the
        top similar users."""
        anime_to_score = {}
        for anime in candidate_anime:
            total_score = 0.0
            total_similarity = 0.0
            contributors = 0
            for user in self.get_neighbours(anime):
                if user in top_users:
                    total_score += top_users[user] * self.get_weight(user, anime)
                    total_similarity += top_users[user]
                    contributors += 1
            if total_similarity != 0 and contributors >= 2:
                adjusted_score = (total_score / total_similarity) * (contributors / (contributors + 1))
                normalized_score = adjusted_score / 10
                normalized_score = max(0.0, min(1.0, normalized_score))
                anime_to_score[anime] = round(normalized_score, 6)
        return anime_to_score

    def recommend_anime_weighted(self, inputted_ratings: dict[str, int], limit_users: int = 50, limit_anime: int = 20) \
            -> dict[str, float]:
        """Return a dict mapping recommended anime titles to their recommendation scores,
        in descending order of score, with at most <limit_anime> results.

        The returned dict keys does not contain:
            - the input anime itself
            - any anime with a similarity score of 0 to the input anime
            - any duplicates
            - any vertices that represents a user (instead of an anime)

        Up to <limit_anime> anime are returned, ordered from highest to lowest score.
        Fewer than <limit_anime> anime may be returned if not enough valid candidates exist.

        Preconditions:
            - all(anime in self._vertices for anime in inputted_ratings)
            - all(self._vertices[anime].kind == 'anime' for anime in inputted_ratings)
            - limit_anime >= 1 and limit_users >= 1
        """
        self.add_input_user(inputted_ratings, "inputted_user")
        top_users = self.get_top_similar_users("inputted_user", limit_users)
        candidate_anime = self._get_candidate_anime(top_users, list(inputted_ratings.keys()))
        normalized_scores = self._score_candidate_anime(candidate_anime, top_users)
        sorted_anime = sorted(normalized_scores.items(), key=lambda x: x[1], reverse=True)
        return dict(sorted_anime[:limit_anime])


def load_user_graph(reviews_file: str, anime_file: str) -> WeightedGraph:
    """Return a user and anime graph corresponding to the given datasets. Note: the graph loads
    every single user with at least two anime reviewed.

    Skips creating graph edges/vertices when user_file contains an anime that does not exist in the anime_file

    Preconditions:
        - user_file is the path to a CSV file corresponding to the user data
        - anime_file is the path to a CSV file corresponding to the anime data

    >>> g = load_user_graph('data/reviews_small.csv', 'data/animes.csv')
    >>> len(g.get_all_vertices(kind='anime'))
    2
    >>> len(g.get_all_vertices(kind='user'))
    1
    """
    g = WeightedGraph()
    user_map = data_sanitization.clean_reviews(reviews_file)
    anime_map = data_sanitization.get_anime_id_title_map(anime_file, user_map)
    for user in user_map:
        g.add_vertex(user, "user")
        for anime, weight in user_map[user]:
            try:
                anime_title = anime_map[anime]
            except KeyError:
                continue
            g.add_vertex(anime_title, "anime")
            g.add_edge(user, anime_title, weight)
    return g


def load_custom_user_graph(num_top_users: int, total_graph: WeightedGraph, inputted_ratings: dict[str, int]) \
        -> WeightedGraph:
    """Return a graph containing the inputted user and the top similar users.
    Edges connect the inputted user to each top similar user, and each edge
    weight is that user's similarity score with the inputted user.
    """
    g = WeightedGraph()
    input_username = "inputted_user"
    total_graph.add_input_user(inputted_ratings, input_username)
    top_users = total_graph.get_top_similar_users(input_username, num_top_users)
    g.add_vertex(input_username, "user")
    for user in top_users:
        g.add_vertex(user, 'user')
        g.add_edge(user, input_username, top_users[user])

    return g


if __name__ == '__main__':
    pass
    # import python_ta.contracts
    # python_ta.contracts.check_all_contracts()
    #
    # import doctest
    # doctest.testmod()
    #
    # import python_ta
    # python_ta.check_all(config={
    #     'max-line-length': 120,
    #     'extra-imports': ['data_sanitization', 'user_graph'],
    #     'max-nested-blocks': 4
    # })
